import {
  User,
  Lead,
  LeadFootprint,
  EmailVerification,
  Transaction,
  Customer,
  Ticket,
  ActivityLog,
  AuditLog,
  CallLog,
} from "@/types";

export const INITIAL_USERS: User[] = [
  {
    id: "usr_superadmin",
    tenantId: "tenant_travelocase",
    username: "superadmin",
    email: "super.admin@travelocase.com",
    name: "Alex Thorne (Super Admin)",
    role: "SUPER_ADMIN",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "100",
    rcDirectNumber: "+1 (800) 555-0100",
    rcStatus: "AVAILABLE",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "usr_admin",
    tenantId: "tenant_travelocase",
    departmentId: "dept_admin",
    username: "admin.rachel",
    email: "admin.rachel@travelocase.com",
    name: "Rachel Vance (Operations Admin)",
    role: "ADMIN",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "103",
    rcDirectNumber: "+1 (800) 555-0103",
    rcStatus: "AVAILABLE",
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "usr_sales_mgr",
    tenantId: "tenant_travelocase",
    departmentId: "dept_sales",
    username: "marcus.mgr",
    email: "marcus.brooks@travelocase.com",
    name: "Marcus Brooks (Sales Director & Manager)",
    role: "SALES_MANAGER",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "102",
    rcDirectNumber: "+1 (800) 555-0102",
    rcStatus: "AVAILABLE",
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "usr_sales_agent1",
    tenantId: "tenant_travelocase",
    departmentId: "dept_sales",
    username: "sarah.agent",
    email: "sarah.chen@travelocase.com",
    name: "Sarah Chen (Senior Flight Specialist)",
    role: "SALES_AGENT",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "101",
    rcDirectNumber: "+1 (800) 555-0101",
    rcStatus: "AVAILABLE",
    createdAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "usr_sales_agent2",
    tenantId: "tenant_travelocase",
    departmentId: "dept_sales",
    username: "david.agent",
    email: "david.miller@travelocase.com",
    name: "David Miller (Travel Booking Agent)",
    role: "SALES_AGENT",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "104",
    rcDirectNumber: "+1 (800) 555-0104",
    rcStatus: "AVAILABLE",
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "usr_charging_mgr",
    tenantId: "tenant_travelocase",
    departmentId: "dept_charging",
    username: "elena.mgr",
    email: "elena.rostova@travelocase.com",
    name: "Elena Rostova (Head of Ticketing & Charging)",
    role: "CHARGING_MANAGER",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "105",
    rcDirectNumber: "+1 (800) 555-0105",
    rcStatus: "AVAILABLE",
    createdAt: "2026-01-18T00:00:00Z",
  },
  {
    id: "usr_charging_op",
    tenantId: "tenant_travelocase",
    departmentId: "dept_charging",
    username: "lucas.op",
    email: "lucas.silva@travelocase.com",
    name: "Lucas Silva (Ticketing & Card Charge Ops)",
    role: "CHARGING_OPERATOR",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "106",
    rcDirectNumber: "+1 (800) 555-0106",
    rcStatus: "AVAILABLE",
    createdAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "usr_cs_mgr",
    tenantId: "tenant_travelocase",
    departmentId: "dept_cs",
    username: "chloe.mgr",
    email: "chloe.dupont@travelocase.com",
    name: "Chloe Dupont (VP Customer Success)",
    role: "CS_MANAGER",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "107",
    rcDirectNumber: "+1 (800) 555-0107",
    rcStatus: "AVAILABLE",
    createdAt: "2026-01-22T00:00:00Z",
  },
  {
    id: "usr_cs_agent",
    tenantId: "tenant_travelocase",
    departmentId: "dept_cs",
    username: "sam.agent",
    email: "sam.patel@travelocase.com",
    name: "Sam Patel (Concierge & Onboarding Specialist)",
    role: "CS_AGENT",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    isActive: true,
    rcExtension: "108",
    rcDirectNumber: "+1 (800) 555-0108",
    rcStatus: "AVAILABLE",
    createdAt: "2026-02-15T00:00:00Z",
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead_yak33k",
    bookingNumber: 1001,
    bookingId: "YAK33K",
    tenantId: "tenant_travelocase",
    assignedToId: "usr_sales_agent1",
    assignedToName: "Sarah Chen",
    name: "Jose Emilio Cruz Gomez",
    email: "josecruz959@gmail.com",
    alternateEmail: "",
    phone: "+1-2537548903",
    alternatePhone: "",
    address: "9 Delafield Dr",
    state: "MISSOURI",
    city: "Fort Leonard Wood",
    postalCode: "65473",
    country: "US",
    company: "Cruz Family Travels",
    status: "SALE",
    dealValue: 1850,
    ticketPrice: 1420,
    salePrice: 1850,
    mco: 430,
    currency: "USD",
    notes: "Family roundtrip booking via Chicago and Dallas. 4 passengers manifest verified.",
    authEmailSent: true,
    authCallConfirmed: true,
    bookingDetails: {
      origin: "ELP (El Paso)",
      destination: "CLE (Cleveland)",
      tripType: "ROUND_TRIP",
      departureDate: "2026-07-16",
      returnDate: "2026-07-20",
      airline: "American Airlines",
      flightNumber: "AA-3484",
      cabinClass: "ECONOMY",
      pnrCode: "YAK33K",
      passengers: [
        {
          id: "pax_cruz_01",
          fullName: "Jose Emilio Cruz Gomez",
          title: "Mr",
          firstName: "Jose",
          middleName: "Emilio",
          lastName: "CruzGomez",
          type: "Adult",
          gender: "Male",
          dob: "10/10/1978",
          nationality: "US",
          seatPreference: "12A",
          mealPreference: "Standard",
        },
        {
          id: "pax_cruz_02",
          fullName: "Luz Maria Garcia Bruno",
          title: "Ms",
          firstName: "Luz",
          middleName: "Maria",
          lastName: "GarciaBruno",
          type: "Adult",
          gender: "Female",
          dob: "08/27/1981",
          nationality: "US",
          seatPreference: "12B",
          mealPreference: "Standard",
        },
        {
          id: "pax_cruz_03",
          fullName: "Josiel Leonardo Cruz Garcia",
          title: "Mr",
          firstName: "Josiel",
          middleName: "Leonardo",
          lastName: "CruzGarcia",
          type: "Adult",
          gender: "Male",
          dob: "12/06/2011",
          nationality: "US",
          seatPreference: "12C",
          mealPreference: "Child Meal",
        },
        {
          id: "pax_cruz_04",
          fullName: "Adian Jose Cruz Garcia",
          title: "Mr",
          firstName: "Adian",
          middleName: "Jose",
          lastName: "CruzGarcia",
          type: "Child",
          gender: "Male",
          dob: "12/25/2015",
          nationality: "US",
          seatPreference: "12D",
          mealPreference: "Child Meal",
        },
      ],
      flights: [
        {
          id: "flt_dep_1",
          airline: "American Airlines",
          airlineCode: "AA",
          flightNumber: "AA-3484",
          origin: "ELP",
          originName: "El Paso International Airport",
          destination: "ORD",
          destinationName: "O'Hare International Airport",
          arrivalTerminal: "Terminal 3",
          departureDate: "Wed, Jul 16",
          departureTime: "06:00 AM",
          arrivalDate: "Wed, Jul 16",
          arrivalTime: "10:14 AM",
          duration: "03h 14m",
          cabinClass: "Economy",
          fareBasis: "GUA0ZNN1",
          flightClass: "G",
          fareType: "SP",
          legGroup: "DEPART",
          routeLabel: "El Paso To Chicago",
          layoverAfter: {
            duration: "03h 21m",
            city: "Chicago",
          },
        },
        {
          id: "flt_dep_2",
          airline: "American Airlines",
          airlineCode: "AA",
          flightNumber: "AA-8253",
          origin: "ORD",
          originName: "O'Hare International Airport",
          departureTerminal: "Terminal 3",
          destination: "CLE",
          destinationName: "Cleveland Hopkins International Airport",
          departureDate: "Wed, Jul 16",
          departureTime: "01:35 PM",
          arrivalDate: "Wed, Jul 16",
          arrivalTime: "03:59 PM",
          duration: "01h 24m",
          cabinClass: "Economy",
          fareBasis: "GUA0ZNN1",
          flightClass: "G",
          fareType: "SP",
          legGroup: "DEPART",
          routeLabel: "Chicago To Cleveland",
        },
        {
          id: "flt_ret_1",
          airline: "American Airlines",
          airlineCode: "AA",
          flightNumber: "AA-2038",
          origin: "CLE",
          originName: "Cleveland Hopkins International Airport",
          destination: "DFW",
          destinationName: "Dallas/Fort Worth International Airport",
          departureDate: "Sun, Jul 20",
          departureTime: "07:30 PM",
          arrivalDate: "Sun, Jul 20",
          arrivalTime: "09:29 PM",
          duration: "02h 59m",
          cabinClass: "Economy",
          fareBasis: "VUA0ZNN1",
          flightClass: "V",
          fareType: "SP",
          legGroup: "RETURN",
          routeLabel: "Cleveland To Dallas",
          layoverAfter: {
            duration: "01h 26m",
            city: "Dallas",
          },
        },
        {
          id: "flt_ret_2",
          airline: "American Airlines",
          airlineCode: "AA",
          flightNumber: "AA-1607",
          origin: "DFW",
          originName: "Dallas/Fort Worth International Airport",
          destination: "ELP",
          destinationName: "El Paso International Airport",
          departureDate: "Sun, Jul 20",
          departureTime: "10:55 PM",
          arrivalDate: "Sun, Jul 20",
          arrivalTime: "11:39 PM",
          duration: "01h 44m",
          cabinClass: "Economy",
          fareBasis: "VUA0ZNN1",
          flightClass: "V",
          fareType: "SP",
          legGroup: "RETURN",
          routeLabel: "Dallas To El Paso",
        },
      ],
    },
    cardDetails: {
      cardholderName: "JOSE EMILIO CRUZ",
      cardNumber: "4111222233334444",
      expiryMonth: "09",
      expiryYear: "2029",
      cvv: "492",
      cardType: "VISA",
      isAccessGrantedToAgent: true,
      accessDurationMinutes: 3,
    },
    createdAt: "2026-06-10T14:20:00Z",
    updatedAt: "2026-06-10T14:30:00Z",
  },
  {
    id: "lead_4intyb",
    bookingNumber: 1002,
    bookingId: "4INTYB",
    tenantId: "tenant_travelocase",
    assignedToId: "usr_sales_agent2",
    assignedToName: "David Miller",
    name: "Esteban Trejo",
    email: "alimousa321@comcast.net",
    alternateEmail: "",
    phone: "+1-4132503262",
    alternatePhone: "",
    address: "21 George st",
    state: "MASSACHUSETTS",
    city: "West Springfield",
    postalCode: "01089",
    country: "US",
    company: "Trejo Logistics",
    status: "QUALIFIED",
    dealValue: 980,
    ticketPrice: 750,
    salePrice: 980,
    mco: 230,
    currency: "USD",
    notes: "Direct booking for Esteban Trejo.",
    authEmailSent: true,
    authCallConfirmed: true,
    bookingDetails: {
      origin: "BDL (Hartford)",
      destination: "ORD (Chicago)",
      tripType: "ONE_WAY",
      departureDate: "2026-08-12",
      airline: "American Airlines",
      flightNumber: "AA-2180",
      cabinClass: "ECONOMY",
      pnrCode: "4INTYB",
      passengers: [
        {
          id: "pax_esteban",
          fullName: "Esteban Trejo",
          title: "Mr",
          firstName: "Esteban",
          lastName: "Trejo",
          type: "Adult",
          gender: "Male",
          dob: "01/03/1996",
          nationality: "US",
          seatPreference: "14C",
        },
      ],
      flights: [
        {
          id: "flt_esteban_1",
          airline: "American Airlines",
          airlineCode: "AA",
          flightNumber: "AA-2180",
          origin: "BDL",
          originName: "Bradley International Airport",
          destination: "ORD",
          destinationName: "O'Hare International Airport",
          departureDate: "Tue, Aug 12",
          departureTime: "08:15 AM",
          arrivalDate: "Tue, Aug 12",
          arrivalTime: "10:05 AM",
          duration: "02h 50m",
          cabinClass: "Economy",
          fareBasis: "NUA0ZNN1",
          flightClass: "N",
          fareType: "SP",
          legGroup: "DEPART",
          routeLabel: "Hartford To Chicago",
        },
      ],
    },
    cardDetails: {
      cardholderName: "ESTEBAN TREJO",
      cardNumber: "5500000000000004",
      expiryMonth: "11",
      expiryYear: "2027",
      cvv: "301",
      cardType: "MASTERCARD",
      isAccessGrantedToAgent: false,
    },
    createdAt: "2026-07-02T11:00:00Z",
    updatedAt: "2026-07-02T11:15:00Z",
  },
  {
    id: "lead_flight_01",
    bookingNumber: 1003,
    bookingId: "#1003",
    tenantId: "tenant_travelocase",
    assignedToId: "usr_sales_agent1",
    assignedToName: "Sarah Chen",
    name: "Lord Harrison Sterling",
    email: "harrison.sterling@sterling-holdings.co.uk",
    phone: "+44 20 7946 0192",
    company: "Sterling Holdings International",
    status: "QUALIFIED",
    ticketPrice: 11500,
    dealValue: 12500,
    salePrice: 12500,
    mco: 1000,
    currency: "USD",
    notes: "Executive business class reservation for 2 passengers.",
    authEmailSent: true,
    authCallConfirmed: true,
    bookingDetails: {
      origin: "JFK (New York)",
      destination: "LHR (London Heathrow)",
      tripType: "ROUND_TRIP",
      departureDate: "2026-10-18",
      returnDate: "2026-10-29",
      airline: "British Airways",
      flightNumber: "BA-178",
      cabinClass: "BUSINESS",
      pnrCode: "NX-BA8912",
      passengers: [
        {
          id: "pax_01",
          fullName: "Lord Harrison Sterling",
          passportNumber: "GB94821094",
          passportExpiry: "2031-06-15",
          nationality: "British (GBR)",
          dob: "1978-04-14",
          gender: "MALE",
          type: "ADULT",
          seatPreference: "2A (Window Club Suite)",
          mealPreference: "Halal / Kosher Diabetic",
          specialAssistance: "None (VIP Priority Boarding)",
          eTicketNumber: "ETKT-125-9482019401",
        },
        {
          id: "pax_02",
          fullName: "Lady Victoria Sterling",
          passportNumber: "GB94821095",
          passportExpiry: "2030-11-20",
          nationality: "British (GBR)",
          dob: "1982-11-09",
          gender: "FEMALE",
          type: "ADULT",
          seatPreference: "2B (Aisle Club Suite)",
          mealPreference: "Vegetarian Lacto-Ovo",
          specialAssistance: "None",
          eTicketNumber: "ETKT-125-9482019402",
        },
      ],
    },
    cardDetails: {
      cardholderName: "HARRISON STERLING",
      cardNumber: "4532890129484242",
      expiryMonth: "08",
      expiryYear: "2028",
      cvv: "891",
      cardType: "VISA",
      isAccessGrantedToAgent: false, // Masked from agent until manager grants
    },
    createdAt: "2026-09-11T09:30:00Z",
    updatedAt: "2026-09-11T09:35:00Z",
    footprint: {
      id: "fp_01",
      leadId: "lead_flight_01",
      ipAddress: "198.51.100.42",
      userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/537.36 Chrome/126.0.0.0 Safari/537.36",
      referrer: "https://www.google.com/search?q=luxury+business+class+flights+london+new+york",
      country: "United Kingdom",
      city: "London",
      utmSource: "google_search",
      utmMedium: "cpc",
      utmCampaign: "luxury_transatlantic_q3",
      clickstream: [
        { timestamp: "2026-09-11T09:15:20Z", event: "ROUTE_SEARCH", url: "/flights/JFK-LHR", metadata: { cabin: "BUSINESS" } },
        { timestamp: "2026-09-11T09:19:10Z", event: "PASSENGER_FORM_FILL", url: "/checkout/passengers", dwellTimeSeconds: 185 },
        { timestamp: "2026-09-11T09:29:45Z", event: "CARD_DETAILS_INPUT", url: "/checkout/payment", metadata: { cardType: "VISA" } },
      ],
      createdAt: "2026-09-11T09:30:00Z",
    },
    emailVerification: {
      id: "ev_01",
      leadId: "lead_flight_01",
      email: "harrison.sterling@sterling-holdings.co.uk",
      spfResult: "PASS",
      dkimResult: "PASS",
      dmarcResult: "PASS",
      mxRecordExists: true,
      smtpCheckValid: true,
      score: 98.0,
      verifiedAt: "2026-09-11T09:30:02Z",
    },
  },
  {
    id: "lead_flight_02",
    bookingNumber: 1002,
    bookingId: "#1002",
    tenantId: "tenant_acme",
    assignedToId: "usr_sales_agent2",
    assignedToName: "David Miller",
    name: "Dr. Kenji Takahashi",
    email: "k.takahashi@tokyo-biotech.jp",
    phone: "+81 3 5555 0199",
    company: "Tokyo BioTech Labs",
    status: "AUTHENTICATION_SENT",
    ticketPrice: 17500,
    dealValue: 0,
    currency: "USD",
    notes: "First Class Roundtrip SFO to Tokyo Haneda. Authentication email sent to passenger.",
    authEmailSent: true,
    authCallConfirmed: false,
    bookingDetails: {
      origin: "SFO (San Francisco)",
      destination: "HND (Tokyo Haneda)",
      tripType: "ROUND_TRIP",
      departureDate: "2026-11-05",
      returnDate: "2026-11-20",
      airline: "All Nippon Airways (ANA)",
      flightNumber: "NH-107",
      cabinClass: "FIRST",
      pnrCode: "NX-NH4401",
      passengers: [
        {
          id: "pax_03",
          fullName: "Dr. Kenji Takahashi",
          passportNumber: "JP88291044",
          passportExpiry: "2032-04-10",
          nationality: "Japanese (JPN)",
          dob: "1972-09-23",
          gender: "MALE",
          type: "ADULT",
          seatPreference: "1A (ANA First Suite)",
          mealPreference: "Japanese Kaiseki Special",
          specialAssistance: "None",
          eTicketNumber: "ETKT-205-8829104401",
        },
      ],
    },
    cardDetails: {
      cardholderName: "KENJI TAKAHASHI",
      cardNumber: "378282246310005",
      expiryMonth: "12",
      expiryYear: "2027",
      cvv: "4921",
      cardType: "AMEX",
      isAccessGrantedToAgent: false,
    },
    createdAt: "2026-09-10T11:20:00Z",
    updatedAt: "2026-09-11T09:00:00Z",
    footprint: {
      id: "fp_02",
      leadId: "lead_flight_02",
      ipAddress: "133.242.18.99",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/127.0.0.0 Safari/537.36",
      referrer: "https://www.ana.co.jp/en/us/",
      country: "Japan",
      city: "Tokyo",
      utmSource: "ana_partner_portal",
      utmMedium: "referral",
      utmCampaign: "first_class_transpacific",
      clickstream: [
        { timestamp: "2026-09-09T11:05:00Z", event: "PAGE_VIEW", url: "/first-class-suites", dwellTimeSeconds: 85 },
        { timestamp: "2026-09-09T11:18:22Z", event: "BOOKING_SUBMITTED", url: "/reserve-flights" },
      ],
      createdAt: "2026-09-09T11:20:00Z",
    },
    emailVerification: {
      id: "ev_02",
      leadId: "lead_flight_02",
      email: "k.takahashi@tokyo-biotech.jp",
      spfResult: "PASS",
      dkimResult: "PASS",
      dmarcResult: "PASS",
      mxRecordExists: true,
      smtpCheckValid: true,
      score: 96.0,
      verifiedAt: "2026-09-09T11:20:05Z",
    },
  },
  {
    id: "lead_flight_03",
    bookingNumber: 1003,
    bookingId: "#1003",
    tenantId: "tenant_acme",
    assignedToId: "usr_sales_agent1",
    assignedToName: "Sarah Chen",
    name: "Elena Rostova",
    email: "elena.r@zurich-finance.ch",
    phone: "+41 22 555 8812",
    company: "Zurich Global Capital",
    status: "CHARGING",
    dealValue: 18900,
    salePrice: 18900,
    ticketPrice: 14700,
    mco: 4200,
    currency: "USD",
    notes: "Marked SALE / FINAL. All passenger and card details verified. Enqueued in Ticketing & Charging desk.",
    authEmailSent: true,
    authCallConfirmed: true,
    bookingDetails: {
      origin: "ORD (Chicago O'Hare)",
      destination: "CDG (Paris Charles de Gaulle)",
      tripType: "ROUND_TRIP",
      departureDate: "2026-10-10",
      returnDate: "2026-10-22",
      airline: "Air France",
      flightNumber: "AF-137",
      cabinClass: "BUSINESS",
      pnrCode: "NX-AF7723",
      passengers: [
        {
          id: "pax_04",
          fullName: "Elena Rostova",
          passportNumber: "CH99482103",
          passportExpiry: "2033-08-12",
          nationality: "Swiss (CHE)",
          dob: "1985-02-18",
          gender: "FEMALE",
          type: "ADULT",
          seatPreference: "3K (Window)",
          mealPreference: "Low Sodium / Gourmet",
          specialAssistance: "None",
          eTicketNumber: "ETKT-057-9948210301",
        },
        {
          id: "pax_05",
          fullName: "Marc Dumont",
          passportNumber: "FR10294819",
          passportExpiry: "2029-05-19",
          nationality: "French (FRA)",
          dob: "1980-07-30",
          gender: "MALE",
          type: "ADULT",
          seatPreference: "3J (Aisle)",
          mealPreference: "French Gourmet Standard",
          specialAssistance: "None",
          eTicketNumber: "ETKT-057-1029481902",
        },
      ],
    },
    cardDetails: {
      cardholderName: "ELENA ROSTOVA",
      cardNumber: "5424180199483311",
      expiryMonth: "09",
      expiryYear: "2029",
      cvv: "349",
      cardType: "MASTERCARD",
      isAccessGrantedToAgent: true,
      grantedByManagerName: "Marcus Brooks (Sales Director)",
      grantedAt: "2026-09-10T14:30:00Z",
    },
    createdAt: "2026-09-08T14:10:00Z",
    updatedAt: "2026-09-11T07:45:00Z",
    footprint: {
      id: "fp_03",
      leadId: "lead_flight_03",
      ipAddress: "194.230.145.12",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/128.0.0.0 Safari/537.36",
      referrer: "https://www.kayak.com/flights/ORD-CDG",
      country: "Switzerland",
      city: "Zurich",
      utmSource: "kayak",
      utmMedium: "meta_search",
      utmCampaign: "fall_paris_deals",
      clickstream: [
        { timestamp: "2026-09-08T14:02:11Z", event: "ROUTE_SELECT", url: "/flights/ORD-CDG" },
        { timestamp: "2026-09-08T14:08:44Z", event: "CARD_PAYMENT_INITIATED", url: "/checkout" },
      ],
      createdAt: "2026-09-08T14:10:00Z",
    },
    emailVerification: {
      id: "ev_03",
      leadId: "lead_flight_03",
      email: "elena.r@zurich-finance.ch",
      spfResult: "PASS",
      dkimResult: "PASS",
      dmarcResult: "PASS",
      mxRecordExists: true,
      smtpCheckValid: true,
      score: 97.0,
      verifiedAt: "2026-09-08T14:10:02Z",
    },
  },
  {
    id: "lead_flight_04",
    bookingNumber: 1004,
    bookingId: "#1004",
    tenantId: "tenant_acme",
    assignedToId: "usr_sales_agent2",
    assignedToName: "David Miller",
    name: "Marcus Aurelius Vance",
    email: "m.vance@rome-defense.it",
    phone: "+39 06 698 12345",
    company: "Rome Defense Systems",
    status: "NEW",
    ticketPrice: 8400,
    dealValue: 0,
    currency: "USD",
    notes: "New inquiry for LAX to Rome FCO business class.",
    bookingDetails: {
      origin: "LAX (Los Angeles)",
      destination: "FCO (Rome Fiumicino)",
      tripType: "ONE_WAY",
      departureDate: "2026-11-12",
      airline: "ITA Airways",
      flightNumber: "AZ-621",
      cabinClass: "BUSINESS",
      pnrCode: "NX-AZ9901",
      passengers: [
        {
          id: "pax_06",
          fullName: "Marcus Aurelius Vance",
          passportNumber: "IT77492100",
          passportExpiry: "2031-10-05",
          nationality: "Italian (ITA)",
          dob: "1983-05-12",
          gender: "MALE",
          type: "ADULT",
          seatPreference: "4D (Aisle)",
          mealPreference: "Gluten-Free / Italian Cuisine",
          specialAssistance: "None",
          eTicketNumber: "ETKT-055-7749210001",
        },
      ],
    },
    cardDetails: {
      cardholderName: "MARCUS A VANCE",
      cardNumber: "4111111111114242",
      expiryMonth: "05",
      expiryYear: "2027",
      cvv: "123",
      cardType: "VISA",
      isAccessGrantedToAgent: false,
    },
    createdAt: "2026-09-11T10:40:00Z",
    updatedAt: "2026-09-11T10:40:00Z",
    footprint: {
      id: "fp_04",
      leadId: "lead_flight_04",
      ipAddress: "35.185.200.18",
      userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15",
      referrer: "https://google.com",
      country: "Italy",
      city: "Rome",
      utmSource: "google_inbound",
      utmMedium: "cpc",
      utmCampaign: "eu_us_routes",
      clickstream: [
        { timestamp: "2026-09-11T10:35:10Z", event: "PAGE_VIEW", url: "/flights/LAX-FCO" },
      ],
      createdAt: "2026-09-11T10:40:00Z",
    },
    emailVerification: {
      id: "ev_04",
      leadId: "lead_flight_04",
      email: "m.vance@rome-defense.it",
      spfResult: "PASS",
      dkimResult: "PASS",
      dmarcResult: "PASS",
      mxRecordExists: true,
      smtpCheckValid: true,
      score: 94.0,
      verifiedAt: "2026-09-11T10:40:03Z",
    },
  },
  {
    id: "lead_flight_05",
    bookingNumber: 1005,
    bookingId: "#1005",
    tenantId: "tenant_acme",
    assignedToId: "usr_sales_agent1",
    assignedToName: "Sarah Chen",
    name: "Beatrice Montgomery",
    email: "bmontgomery@stratos-aero.com",
    phone: "+1 (206) 555-8812",
    company: "Stratos Aerospace",
    status: "SUCCESS",
    dealValue: 36000,
    salePrice: 36000,
    ticketPrice: 28000,
    mco: 8000,
    currency: "USD",
    notes: "Payment validated and captured. Flight e-tickets issued and VIP onboarding ticket dispatched to CS concierge.",
    bookingDetails: {
      origin: "SEA (Seattle)",
      destination: "SIN (Singapore Changi)",
      tripType: "ROUND_TRIP",
      departureDate: "2026-10-01",
      returnDate: "2026-10-15",
      airline: "Singapore Airlines",
      flightNumber: "SQ-27",
      cabinClass: "FIRST",
      pnrCode: "NX-SQ1099",
      passengers: [
        {
          id: "pax_07",
          fullName: "Beatrice Montgomery",
          passportNumber: "US94821033",
          passportExpiry: "2034-01-14",
          nationality: "American (USA)",
          dob: "1975-08-19",
          gender: "FEMALE",
          type: "ADULT",
          seatPreference: "1F (First Class Suite)",
          mealPreference: "Book the Cook - Lobster Thermidor",
          specialAssistance: "None",
          eTicketNumber: "ETKT-618-9482103301",
        },
        {
          id: "pax_08",
          fullName: "Charles Montgomery",
          passportNumber: "US94821034",
          passportExpiry: "2032-09-30",
          nationality: "American (USA)",
          dob: "1971-03-22",
          gender: "MALE",
          type: "ADULT",
          seatPreference: "1K (First Class Suite)",
          mealPreference: "Book the Cook - Wagyu Sirloin",
          specialAssistance: "None",
          eTicketNumber: "ETKT-618-9482103402",
        },
      ],
    },
    cardDetails: {
      cardholderName: "BEATRICE MONTGOMERY",
      cardNumber: "4000056655665556",
      expiryMonth: "11",
      expiryYear: "2028",
      cvv: "782",
      cardType: "VISA",
      isAccessGrantedToAgent: true,
    },
    createdAt: "2026-09-05T09:00:00Z",
    updatedAt: "2026-09-10T16:20:00Z",
    footprint: {
      id: "fp_05",
      leadId: "lead_flight_05",
      ipAddress: "64.104.44.18",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126.0.0.0 Safari/537.36",
      referrer: "https://singaporeair.com",
      country: "United States",
      city: "Seattle, WA",
      utmSource: "bloomberg",
      utmMedium: "display_banner",
      utmCampaign: "q3_first_class_asia",
      clickstream: [
        { timestamp: "2026-09-05T08:45:00Z", event: "SEARCH_ROUTES", url: "/flights/SEA-SIN" },
        { timestamp: "2026-09-05T08:58:30Z", event: "CHECKOUT_COMPLETE", url: "/order-confirmed" },
      ],
      createdAt: "2026-09-05T09:00:00Z",
    },
    emailVerification: {
      id: "ev_05",
      leadId: "lead_flight_05",
      email: "bmontgomery@stratos-aero.com",
      spfResult: "PASS",
      dkimResult: "PASS",
      dmarcResult: "PASS",
      mxRecordExists: true,
      smtpCheckValid: true,
      score: 99.0,
      verifiedAt: "2026-09-05T09:00:05Z",
    },
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "txn_89412",
    tenantId: "tenant_acme",
    leadId: "lead_flight_05",
    leadName: "Beatrice Montgomery (SEA -> SIN Singapore Airlines)",
    customerId: "cust_stratos_01",
    processedById: "usr_charging_op",
    processedByName: "Lucas Silva",
    amount: 36000,
    currency: "USD",
    status: "SUCCESS",
    paymentMethod: "CORPORATE_VISA_COMMERCIAL",
    gatewayTxnId: "GW_AIRLINE_SETTLED_994102",
    verificationChecklist: {
      identityVerified: true,
      fundsAvailable: true,
      fraudRiskScore: 2,
      avsMatch: true,
      cvvMatch: true,
      complianceCleared: true,
    },
    createdAt: "2026-09-10T16:00:00Z",
    updatedAt: "2026-09-10T16:20:00Z",
  },
  {
    id: "txn_89413",
    tenantId: "tenant_acme",
    leadId: "lead_flight_03",
    leadName: "Elena Rostova (ORD -> CDG Air France Business)",
    amount: 18900,
    currency: "USD",
    status: "PROCESSING",
    paymentMethod: "MASTERCARD_WORLD_ELITE",
    gatewayTxnId: "GW_AF_3DSECURE_8819",
    verificationChecklist: {
      identityVerified: true,
      fundsAvailable: true,
      fraudRiskScore: 6,
      avsMatch: true,
      cvvMatch: true,
      complianceCleared: true,
    },
    createdAt: "2026-09-11T09:00:00Z",
    updatedAt: "2026-09-11T09:05:00Z",
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: "cust_stratos_01",
    tenantId: "tenant_acme",
    leadId: "lead_flight_05",
    name: "Beatrice Montgomery",
    email: "bmontgomery@stratos-aero.com",
    phone: "+1 (206) 555-8812",
    company: "Stratos Aerospace",
    tier: "VIP_FIRST_CLASS_GLOBAL",
    healthScore: 100,
    onboardingStatus: "IN_PROGRESS",
    createdAt: "2026-09-10T16:20:00Z",
    updatedAt: "2026-09-11T02:00:00Z",
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "tkt_onb_701",
    tenantId: "tenant_acme",
    customerId: "cust_stratos_01",
    customerName: "Stratos Aerospace (Beatrice Montgomery)",
    leadId: "lead_flight_05",
    assignedToId: "usr_cs_agent",
    assignedToName: "Sam Patel",
    title: "VIP Flight Concierge, Chauffeur & Lounge Access Provisioning",
    description: "Automated ticket dispatched on $36,000 flight settlement for SEA -> SIN First Class (SQ-27). Coordinate airport private terminal escort, seat allocations 1F/1K, and dietary champagne preferences.",
    priority: "HIGH",
    status: "IN_PROGRESS",
    type: "ONBOARDING",
    slaDeadline: new Date(Date.now() + 3.5 * 3600 * 1000).toISOString(),
    isSlaBreached: false,
    createdAt: "2026-09-10T16:20:05Z",
    updatedAt: "2026-09-11T03:00:00Z",
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "act_001",
    tenantId: "tenant_acme",
    entityType: "LEAD",
    entityId: "lead_flight_05",
    actorName: "Flight Ingestion Engine",
    actorRole: "SYSTEM",
    action: "LEAD_INGESTED",
    toState: "NEW",
    metadata: { route: "SEA -> SIN", airline: "Singapore Airlines", amount: 36000 },
    createdAt: "2026-09-05T09:00:00Z",
  },
  {
    id: "act_002",
    tenantId: "tenant_acme",
    entityType: "LEAD",
    entityId: "lead_flight_05",
    actorId: "usr_sales_agent1",
    actorName: "Sarah Chen",
    actorRole: "SALES_AGENT",
    action: "TRANSITION_TO_SALE",
    fromState: "QUALIFIED",
    toState: "SALE",
    metadata: { route: "SEA -> SIN", dealValue: 36000 },
    createdAt: "2026-09-10T15:30:00Z",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud_01",
    tenantId: "tenant_travelocase",
    actorEmail: "sarah.chen@travelocase.com",
    action: "CARD_DETAILS_VIEWED",
    resource: "Lead:lead_flight_03",
    ipAddress: "198.51.100.22",
    status: "SUCCESS",
    payload: { actor: "Sarah Chen", role: "SALES_AGENT", cardLast4: "3311", reason: "Manager clearance granted for ticketing" },
    timestamp: "2026-09-10T15:00:00Z",
  },
  {
    id: "aud_02",
    tenantId: "tenant_travelocase",
    actorEmail: "lucas.silva@travelocase.com",
    action: "TRANSACTION_CHARGE_CAPTURED",
    resource: "Transaction:txn_89412",
    ipAddress: "10.0.4.19",
    status: "SUCCESS",
    payload: { amount: 36000, currency: "USD", gateway: "AIRLINE_COMMERCIAL_SETTLE" },
    timestamp: "2026-09-10T16:20:00Z",
  },
];

export const INITIAL_CALL_LOGS: CallLog[] = [
  {
    id: "call_rc_001",
    tenantId: "tenant_travelocase",
    agentId: "usr_sales_agent1",
    agentName: "Sarah Chen",
    agentExtension: "101",
    agentRole: "SALES_AGENT",
    leadId: "lead_yak33k",
    leadBookingNumber: 1001,
    callerNumber: "+1 (555) 234-8910",
    calleeNumber: "101",
    direction: "INBOUND",
    status: "COMPLETED",
    startTime: new Date(Date.now() - 3600000 * 3).toISOString(),
    endTime: new Date(Date.now() - 3600000 * 3 + 245000).toISOString(),
    durationSeconds: 245,
    disposition: "FLIGHT_RESERVATION_SALE",
    notes: "Inbound call answered on Ext 101. Passenger verified passport number for JFK to LHR route. Agreed to final sale price and confirmed ticketing schedule.",
    leadDetailsEntered: true,
    rcSessionId: "rc_sess_89218731",
    telephonyStatus: "Disconnected",
    recordingUrl: "https://example.com/recordings/rc_call_001.mp3",
    sentiment: "POSITIVE",
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 3 + 245000).toISOString(),
  },
  {
    id: "call_rc_002",
    tenantId: "tenant_travelocase",
    agentId: "usr_sales_agent1",
    agentName: "Sarah Chen",
    agentExtension: "101",
    agentRole: "SALES_AGENT",
    leadId: "lead_flight_02",
    leadBookingNumber: 1002,
    callerNumber: "+1 (800) 555-0101",
    calleeNumber: "+1 (555) 892-1209",
    direction: "OUTBOUND",
    status: "COMPLETED",
    startTime: new Date(Date.now() - 3600000 * 6).toISOString(),
    endTime: new Date(Date.now() - 3600000 * 6 + 182000).toISOString(),
    durationSeconds: 182,
    disposition: "PRICE_QUOTE_GIVEN",
    notes: "Outbound follow-up via RingCentral dialer. Provided business class upgrade quote on Emirates flight. Customer will review and call back by afternoon.",
    leadDetailsEntered: true,
    rcSessionId: "rc_sess_89218732",
    telephonyStatus: "Disconnected",
    recordingUrl: "https://example.com/recordings/rc_call_002.mp3",
    sentiment: "NEUTRAL",
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 6 + 182000).toISOString(),
  },
  {
    id: "call_rc_003",
    tenantId: "tenant_travelocase",
    agentId: "usr_sales_agent1",
    agentName: "Sarah Chen",
    agentExtension: "101",
    agentRole: "SALES_AGENT",
    callerNumber: "+1 (555) 774-9912",
    calleeNumber: "101",
    direction: "INBOUND",
    status: "MISSED",
    startTime: new Date(Date.now() - 3600000 * 12).toISOString(),
    durationSeconds: 0,
    disposition: "LEFT_VOICEMAIL",
    notes: "Missed call during shift handoff. Voicemail audio received: Customer inquiring about flight rescheduling fee.",
    leadDetailsEntered: false,
    rcSessionId: "rc_sess_89218733",
    telephonyStatus: "Disconnected",
    sentiment: "NEUTRAL",
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: "call_rc_004",
    tenantId: "tenant_travelocase",
    agentId: "usr_sales_mgr",
    agentName: "Marcus Brooks",
    agentExtension: "102",
    agentRole: "SALES_MANAGER",
    callerNumber: "+1 (800) 555-0102",
    calleeNumber: "+1 (555) 671-3329",
    direction: "OUTBOUND",
    status: "COMPLETED",
    startTime: new Date(Date.now() - 3600000 * 20).toISOString(),
    endTime: new Date(Date.now() - 3600000 * 20 + 312000).toISOString(),
    durationSeconds: 312,
    disposition: "PAYMENT_CONFIRMATION",
    notes: "Manager escalation call. Cleared card verification checklist with client and sent authorization receipt.",
    leadDetailsEntered: true,
    rcSessionId: "rc_sess_89218734",
    telephonyStatus: "Disconnected",
    sentiment: "POSITIVE",
    createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 20 + 312000).toISOString(),
  },
];

